// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var OcticonsReact = require("@githubprimer/octicons-react");

function classOfIcon(param) {
  switch (param) {
    case 0 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Alert"]);
    case 1 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowDown"]);
    case 2 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowLeft"]);
    case 3 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowRight"]);
    case 4 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowSmallDown"]);
    case 5 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowSmallLeft"]);
    case 6 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowSmallRight"]);
    case 7 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowSmallUp"]);
    case 8 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ArrowUp"]);
    case 9 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Beaker"]);
    case 10 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Bell"]);
    case 11 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Bold"]);
    case 12 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Book"]);
    case 13 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Bookmark"]);
    case 14 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Briefcase"]);
    case 15 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Broadcast"]);
    case 16 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Browser"]);
    case 17 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Bug"]);
    case 18 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Calendar"]);
    case 19 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Check"]);
    case 20 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Checklist"]);
    case 21 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ChevronDown"]);
    case 22 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ChevronLeft"]);
    case 23 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ChevronRight"]);
    case 24 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ChevronUp"]);
    case 25 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["CircleSlash"]);
    case 26 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["CircuitBoard"]);
    case 27 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Clippy"]);
    case 28 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Clock"]);
    case 29 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["CloudDownload"]);
    case 30 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["CloudUpload"]);
    case 31 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Code"]);
    case 32 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Comment"]);
    case 33 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["CommentDiscussion"]);
    case 34 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["CreditCard"]);
    case 35 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Dash"]);
    case 36 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Dashboard"]);
    case 37 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Database"]);
    case 38 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DesktopDownload"]);
    case 39 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DeviceCamera"]);
    case 40 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DeviceCameraVideo"]);
    case 41 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DeviceDesktop"]);
    case 42 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DeviceMobile"]);
    case 43 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Diff"]);
    case 44 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DiffAdded"]);
    case 45 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DiffIgnored"]);
    case 46 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DiffModified"]);
    case 47 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DiffRemoved"]);
    case 48 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["DiffRenamed"]);
    case 49 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Ellipsis"]);
    case 50 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Eye"]);
    case 51 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["File"]);
    case 52 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileBinary"]);
    case 53 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileCode"]);
    case 54 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileDirectory"]);
    case 55 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileMedia"]);
    case 56 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FilePdf"]);
    case 57 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileSubmodule"]);
    case 58 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileSymlinkDirectory"]);
    case 59 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileSymlinkFile"]);
    case 60 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["FileZip"]);
    case 61 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Flame"]);
    case 62 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Fold"]);
    case 63 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Gear"]);
    case 64 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Gift"]);
    case 65 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Gist"]);
    case 66 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["GistSecret"]);
    case 67 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["GitBranch"]);
    case 68 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["GitCommit"]);
    case 69 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["GitCompare"]);
    case 70 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["GitMerge"]);
    case 71 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["GitPullRequest"]);
    case 72 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Globe"]);
    case 73 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Grabber"]);
    case 74 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Graph"]);
    case 75 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Heart"]);
    case 76 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["History"]);
    case 77 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Home"]);
    case 78 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["HorizontalRule"]);
    case 79 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Hubot"]);
    case 80 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Inbox"]);
    case 81 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Info"]);
    case 82 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["IssueClosed"]);
    case 83 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["IssueOpened"]);
    case 84 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["IssueReopened"]);
    case 85 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Italic"]);
    case 86 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Jersey"]);
    case 87 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["KebabHorizontal"]);
    case 88 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["KebabVertical"]);
    case 89 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Key"]);
    case 90 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Keyboard"]);
    case 91 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Law"]);
    case 92 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["LightBulb"]);
    case 93 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Link"]);
    case 94 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["LinkExternal"]);
    case 95 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ListOrdered"]);
    case 96 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ListUnordered"]);
    case 97 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Location"]);
    case 98 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Lock"]);
    case 99 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["LogoGist"]);
    case 100 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["LogoGithub"]);
    case 101 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Mail"]);
    case 102 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["MailRead"]);
    case 103 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["MarkGithub"]);
    case 104 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Markdown"]);
    case 105 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Megaphone"]);
    case 106 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Mention"]);
    case 107 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Milestone"]);
    case 108 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Mirror"]);
    case 109 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["MortarBoard"]);
    case 110 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Mute"]);
    case 111 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["NoNewline"]);
    case 112 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Note"]);
    case 113 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Octoface"]);
    case 114 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Organization"]);
    case 115 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Package"]);
    case 116 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Paintcan"]);
    case 117 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Pencil"]);
    case 118 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Person"]);
    case 119 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Pin"]);
    case 120 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Plug"]);
    case 121 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Plus"]);
    case 122 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["PlusSmall"]);
    case 123 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["PrimitiveDot"]);
    case 124 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["PrimitiveSquare"]);
    case 125 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Project"]);
    case 126 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Pulse"]);
    case 127 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Question"]);
    case 128 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Quote"]);
    case 129 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["RadioTower"]);
    case 130 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Reply"]);
    case 131 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Repo"]);
    case 132 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["RepoClone"]);
    case 133 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["RepoForcePush"]);
    case 134 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["RepoForked"]);
    case 135 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["RepoPull"]);
    case 136 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["RepoPush"]);
    case 137 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Report"]);
    case 138 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Rocket"]);
    case 139 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Rss"]);
    case 140 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Ruby"]);
    case 141 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ScreenFull"]);
    case 142 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ScreenNormal"]);
    case 143 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Search"]);
    case 144 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Server"]);
    case 145 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Settings"]);
    case 146 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Shield"]);
    case 147 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["SignIn"]);
    case 148 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["SignOut"]);
    case 149 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Smiley"]);
    case 150 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Squirrel"]);
    case 151 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Star"]);
    case 152 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Stop"]);
    case 153 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Sync"]);
    case 154 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Tag"]);
    case 155 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Tasklist"]);
    case 156 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Telescope"]);
    case 157 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Terminal"]);
    case 158 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["TextSize"]);
    case 159 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["ThreeBars"]);
    case 160 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Thumbsdown"]);
    case 161 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Thumbsup"]);
    case 162 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Tools"]);
    case 163 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Trashcan"]);
    case 164 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["TriangleDown"]);
    case 165 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["TriangleLeft"]);
    case 166 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["TriangleRight"]);
    case 167 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["TriangleUp"]);
    case 168 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Unfold"]);
    case 169 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Unmute"]);
    case 170 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Unverified"]);
    case 171 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Verified"]);
    case 172 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Versions"]);
    case 173 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Watch"]);
    case 174 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["X"]);
    case 175 : 
        return Js_primitive.undefined_to_opt(OcticonsReact["Zap"]);
    
  }
}

function stringOfSize(param) {
  if (param !== undefined) {
    switch (param) {
      case 0 : 
          return "small";
      case 1 : 
          return "medium";
      case 2 : 
          return "large";
      
    }
  }
  
}

function stringOfVerticalAlign(param) {
  if (param !== undefined) {
    switch (param) {
      case 0 : 
          return "middle";
      case 1 : 
          return "text-bottom";
      case 2 : 
          return "text-top";
      case 3 : 
          return "top";
      
    }
  }
  
}

function make(icon, size, verticalAlign, children) {
  return ReasonReact.wrapJsForReason(OcticonsReact.default, {
              icon: Js_null_undefined.fromOption(classOfIcon(icon)),
              size: Js_null_undefined.fromOption(stringOfSize(size)),
              verticalAlign: Js_null_undefined.fromOption(stringOfVerticalAlign(verticalAlign))
            }, children);
}

exports.classOfIcon = classOfIcon;
exports.stringOfSize = stringOfSize;
exports.stringOfVerticalAlign = stringOfVerticalAlign;
exports.make = make;
/* ReasonReact Not a pure module */
