// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var OcticonsReact = require("@githubprimer/octicons-react");

function classOfIcon() {
  return OcticonsReact.Sync;
}

function stringOfSize(param) {
  if (param !== undefined) {
    switch (param) {
      case 0 : 
          return "small";
      case 1 : 
          return "medium";
      case 2 : 
          return "large";
      
    }
  }
  
}

function stringOfVerticalAlign(param) {
  if (param !== undefined) {
    switch (param) {
      case 0 : 
          return "middle";
      case 1 : 
          return "text-bottom";
      case 2 : 
          return "text-top";
      case 3 : 
          return "top";
      
    }
  }
  
}

function make(_, size, verticalAlign, children) {
  return ReasonReact.wrapJsForReason(OcticonsReact.default, {
              icon: OcticonsReact.Sync,
              size: Js_null_undefined.fromOption(stringOfSize(size)),
              verticalAlign: Js_null_undefined.fromOption(stringOfVerticalAlign(verticalAlign))
            }, children);
}

exports.classOfIcon = classOfIcon;
exports.stringOfSize = stringOfSize;
exports.stringOfVerticalAlign = stringOfVerticalAlign;
exports.make = make;
/* ReasonReact Not a pure module */
